language: go
sudo: false
go:
  - 1.x
  - "1.10"
  - 1.11.x
  - master
before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/fatih/color
  - go get github.com/ivopetiz/network-scanner
script:
  - $GOPATH/bin/goveralls -service=travis-ci
